name: LifeFFACore
version: '${version}'
main: lifeffa.org.example.lifeffacore.LifeFFACore
api-version: 1.15

commands:
  ffajoin:
    description: "join lifeffa"
    aliases: fjoin
    permission: lifeffacore.ffajoin