name: LifeFFACore
version: '${version}'
main: lifeffa.org.example.lifeffacore.LifeFFACore
api-version: 1.15

commands:
  ffajoin:
    description: "join lifeffa"
    aliases: fjoin
    permission: lifeffacore.ffajoin
  pointsconvert:
    description: "convert LifeFFAPoints"
    aliases: pconvert
    permission: lifeffacore.pointsconvert
  ffapoints:
    description: "points management"
    permission: lifeffacore.ffapoints
  killranking:
    description: "view kill rankings"
    aliases: kranking
    permission: lifeffacore.killranking
  ffagetitem:
    description: "get item"
    permission: lifeffacore.ffagetitem
  checkplayers:
    aliases: fcp
    description: "check all players in a lifeFFA"
    permission: lifeffacore.ggacheckplayers
  dailymission:
    aliases: daily
    description: "check dailymission"
    permission: lifeffacore.dailymission
  ffacheckitem:
    aliases: fci
    description: "check item MYTHIC_TYPE"
    permission: lifeffacore.ffacheckitem



